language: node_js
node_js:
  - "14"
install: npm install
script:
  - npm run build
  - docker build -t easy-blog-react .  
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push easy-blog-react
