language: node_js
node_js:
  - "14"
install: npm install
script:
  - npm run build
  - docker build -t codereporter/easy-blog-react:latest .  
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push codereporter/easy-blog-react:latest
